SELECT NAME
FROM sys.databases

CREATE DATABASE Resit;

--Dion Finnerty 103545669--

/*TASK 1

SUBJECT(SubjCode, Description)
PRIMARY  KEY (SubjCode)

TEACHER(StaffId, Surname, GivenName)
PRIMARY KEY (StaffId)

STUDENT(StudentId, Surname, GivenName, Gender)
PRIMARY KEY (StudentId)


SUBJECTOFFERING(Year, Semester, SubjCode, StaffId, Fee)
PRIMARY KEY (Year, Semester)
FOREIGN KEY (SubjCode) REFERENCES SUBJECT
FOREIGN KEY (StaffId) REFERENCES TEACHER

ENROLMENT(StudentId, Year, Semester, DateEnrolled, Grade)
FOREIGN KEY (Year, Semester) REFERENCES SUBJECTOFFERING
FOREIGN KEY (StudentId) REFERENCES STUDENT

*/

CREATE TABLE SUBJECT5669 (
    SubjCode NVARCHAR(100), 
    [Description] NVARCHAR(500),
    PRIMARY  KEY (SubjCode)
)

CREATE TABLE TEACHER5669(
    StaffId INT, 
    Surname NVARCHAR(100) NOT NULL, 
    GivenName NVARCHAR(100) NOT NULL,
    PRIMARY KEY (StaffId),
    CONSTRAINT CHK_TEACHER_STAFFID CHECK (StaffId BETWEEN 10000000 AND 99999999)
)

CREATE TABLE STUDENT5669(
    StudentId NVARCHAR(10), 
    Surname NVARCHAR(100) NOT NULL, 
    GivenName NVARCHAR(100) NOT NULL, 
    Gender  NVARCHAR(1)
    PRIMARY KEY (StudentId)
    CONSTRAINT CHK_STUDENT_GENDER CHECK (Gender IN('M', 'F', 'I'))
)

CREATE TABLE SUBJECTOFFERING5669(
    [Year] INT , 
    Semester INT, 
    SubjCode NVARCHAR(100), 
    StaffId INT, 
    Fee MONEY NOT NULL,
    PRIMARY KEY ([Year], Semester),
    FOREIGN KEY (SubjCode) REFERENCES SUBJECT5669,
    FOREIGN KEY (StaffId) REFERENCES TEACHER5669,
    CONSTRAINT CHK_SUBJECTOFFERING_YEAR CHECK ([Year] BETWEEN 1000 AND 9999),
    CONSTRAINT CHK_SUBJECTOFFERING_SEMESTER CHECK (Semester IN (1,2)),
    CONSTRAINT CHK_SUBJECTOFFERING_FEE CHECK (Fee > 0)
)

CREATE TABLE ENROLMENT5669(
    StudentId NVARCHAR(10),
    [Year] INT, 
    Semester INT, 
    DateEnrolled DATE, 
    Grade NVARCHAR(2) DEFAULT NULL,
    FOREIGN KEY ([Year], Semester) REFERENCES SUBJECTOFFERING5669,
    FOREIGN KEY (StudentId) REFERENCES STUDENT5669,
    CONSTRAINT CHK_ENROLMENT_GRADE CHECK (Grade IN ('N', 'P', 'C', 'D', 'HD'))
)

DROP TABLE SUBJECT5669

DROP TABLE TEACHER5669

DROP TABLE STUDENT5669

DROP TABLE SUBJECTOFFERING5669

DROP TABLE ENROLMENT5669

